const vocabularioLugares = {

   // ==================== PAÍSES ====================
"pais": "https://static.arasaac.org/pictograms/35431/35431_300.png",
"argentina": "https://static.arasaac.org/pictograms/29590/29590_300.png",
"españa": "https://static.arasaac.org/pictograms/28967/28967_300.png",
"uruguay": "",
"chile": "",
"brasil": "",
"paraguay": "",
"bolivia": "",
"perú": "",
"ecuador": "",
"colombia": "",
"venezuela": "",
"méxico": "",
"estados unidos": "",
"canadá": "",
"cuba": "",
"república dominicana": "",
"puerto rico": "",
"panamá": "",
"costa rica": "",
"guatemala": "",
"el salvador": "",
"honduras": "",
"nicaragua": "",
"francia": "",
"italia": "",
"alemania": "",
"inglaterra": "",
"portugal": "",
"rusia": "",
"china": "",
"japón": "",
"corea del sur": "",
"india": "",
"egipto": "",
"marruecos": "",
"túnez": "",
"turquía": "",
"australia": "",
"nueva zelanda": "",
"sudáfrica": "",


// ==================== PROVINCIAS ====================

"buenos aires": "",
"catamarca": "",
"chaco": "",
"chubut": "",
"córdoba": "",
"corrientes": "",
"entre ríos": "",
"formosa": "",
"jujuy": "",
"la pampa": "",
"la rioja": "",
"mendoza": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Provincia_de_Mendoza_%28Argentina%29.png/500px-Provincia_de_Mendoza_%28Argentina%29.png",
"misiones": "",
"neuquén": "",
"río negro": "",
"salta": "",
"san juan": "",
"san luis": "",
"santa cruz": "",
"santa fe": "",
"santiago del estero": "",
"tierra del fuego": "",
"tucumán": "",
"ciudad autónoma de buenos aires": "",
"caba": "",


    // ==================== LUGARES ====================

    "escuela": "https://static.arasaac.org/pictograms/3082/3082_300.png",
    "plaza": "https://static.arasaac.org/pictograms/2859/2859_300.png",
    "casa": "https://static.arasaac.org/pictograms/2317/2317_300.png",
    "cine": "https://static.arasaac.org/pictograms/30387/30387_300.png",
    "pileta": "https://static.arasaac.org/pictograms/3142/3142_300.png",
    "lugar": "https://static.arasaac.org/pictograms/9819/9819_300.png",
    "colonia": "https://static.arasaac.org/pictograms/11222/11222_300.png",
    "río": "https://static.arasaac.org/pictograms/2811/2811_300.png",
    "montaña": "https://static.arasaac.org/pictograms/2909/2909_300.png",
    "montañas": "https://static.arasaac.org/pictograms/2909/2909_300.png",
    "hotel": "",
    "hospital": "",
    "clínica": "",
    "consultorio": "",
    "veterinaria": "",
   "campo": "https://static.arasaac.org/pictograms/2683/2683_300.png",
   "ciudad": "https://static.arasaac.org/pictograms/2704/2704_300.png",

};

Object.assign(pictogramas, vocabularioLugares);
